# Generated by Django 3.0.7 on 2020-06-20 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to=profiles.utils.photo_path)),
                ('bio', models.TextField()),
                ('website_url', models.CharField(blank=True, max_length=1000)),
                ('linkedin_url', models.CharField(blank=True, max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to=profiles.utils.photo_path)),
                ('bio', models.TextField()),
                ('github_url', models.CharField(blank=True, max_length=300)),
                ('linkedin_url', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to=profiles.utils.photo_path)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(related_name='tags', to='profiles.Employee')),
                ('employers', models.ManyToManyField(related_name='tags', to='profiles.Employer')),
            ],
        ),
    ]
