# Generated by Django 3.0.7 on 2020-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200621_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='interested_employers',
            field=models.ManyToManyField(related_name='interested_in', to='profiles.Employer'),
        ),
        migrations.AddField(
            model_name='employer',
            name='interested_employees',
            field=models.ManyToManyField(related_name='interested_in', to='profiles.Employee'),
        ),
    ]
