# Generated by Django 3.0.7 on 2020-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200621_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, upload_to='company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employees'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employers'),
        ),
    ]
